// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: transit.proto

package protodata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       *string                `protobuf:"bytes,1,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	ServiceId     *string                `protobuf:"bytes,2,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	TripId        *string                `protobuf:"bytes,3,opt,name=trip_id,json=tripId" json:"trip_id,omitempty"`
	TripHeadsign  *string                `protobuf:"bytes,4,opt,name=trip_headsign,json=tripHeadsign" json:"trip_headsign,omitempty"`
	DirectionId   *int32                 `protobuf:"varint,5,opt,name=direction_id,json=directionId" json:"direction_id,omitempty"`
	BlockId       *string                `protobuf:"bytes,6,opt,name=block_id,json=blockId" json:"block_id,omitempty"`
	ShapeId       *string                `protobuf:"bytes,7,opt,name=shape_id,json=shapeId" json:"shape_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripProto) Reset() {
	*x = TripProto{}
	mi := &file_transit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripProto) ProtoMessage() {}

func (x *TripProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripProto.ProtoReflect.Descriptor instead.
func (*TripProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{0}
}

func (x *TripProto) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *TripProto) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *TripProto) GetTripId() string {
	if x != nil && x.TripId != nil {
		return *x.TripId
	}
	return ""
}

func (x *TripProto) GetTripHeadsign() string {
	if x != nil && x.TripHeadsign != nil {
		return *x.TripHeadsign
	}
	return ""
}

func (x *TripProto) GetDirectionId() int32 {
	if x != nil && x.DirectionId != nil {
		return *x.DirectionId
	}
	return 0
}

func (x *TripProto) GetBlockId() string {
	if x != nil && x.BlockId != nil {
		return *x.BlockId
	}
	return ""
}

func (x *TripProto) GetShapeId() string {
	if x != nil && x.ShapeId != nil {
		return *x.ShapeId
	}
	return ""
}

type RouteProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RouteId        *string                `protobuf:"bytes,1,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	AgencyId       *string                `protobuf:"bytes,2,opt,name=agency_id,json=agencyId" json:"agency_id,omitempty"`
	RouteShortName *string                `protobuf:"bytes,3,opt,name=route_short_name,json=routeShortName" json:"route_short_name,omitempty"`
	RouteLongName  *string                `protobuf:"bytes,4,opt,name=route_long_name,json=routeLongName" json:"route_long_name,omitempty"`
	RouteDesc      *string                `protobuf:"bytes,5,opt,name=route_desc,json=routeDesc" json:"route_desc,omitempty"`
	RouteType      *int32                 `protobuf:"varint,6,opt,name=route_type,json=routeType" json:"route_type,omitempty"`
	RouteUrl       *string                `protobuf:"bytes,7,opt,name=route_url,json=routeUrl" json:"route_url,omitempty"`
	RouteColor     *string                `protobuf:"bytes,8,opt,name=route_color,json=routeColor" json:"route_color,omitempty"`
	RouteTextColor *string                `protobuf:"bytes,9,opt,name=route_text_color,json=routeTextColor" json:"route_text_color,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteProto) Reset() {
	*x = RouteProto{}
	mi := &file_transit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteProto) ProtoMessage() {}

func (x *RouteProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteProto.ProtoReflect.Descriptor instead.
func (*RouteProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{1}
}

func (x *RouteProto) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *RouteProto) GetAgencyId() string {
	if x != nil && x.AgencyId != nil {
		return *x.AgencyId
	}
	return ""
}

func (x *RouteProto) GetRouteShortName() string {
	if x != nil && x.RouteShortName != nil {
		return *x.RouteShortName
	}
	return ""
}

func (x *RouteProto) GetRouteLongName() string {
	if x != nil && x.RouteLongName != nil {
		return *x.RouteLongName
	}
	return ""
}

func (x *RouteProto) GetRouteDesc() string {
	if x != nil && x.RouteDesc != nil {
		return *x.RouteDesc
	}
	return ""
}

func (x *RouteProto) GetRouteType() int32 {
	if x != nil && x.RouteType != nil {
		return *x.RouteType
	}
	return 0
}

func (x *RouteProto) GetRouteUrl() string {
	if x != nil && x.RouteUrl != nil {
		return *x.RouteUrl
	}
	return ""
}

func (x *RouteProto) GetRouteColor() string {
	if x != nil && x.RouteColor != nil {
		return *x.RouteColor
	}
	return ""
}

func (x *RouteProto) GetRouteTextColor() string {
	if x != nil && x.RouteTextColor != nil {
		return *x.RouteTextColor
	}
	return ""
}

type ShapeProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShapeId           *string                `protobuf:"bytes,1,opt,name=shape_id,json=shapeId" json:"shape_id,omitempty"`
	ShapePtLat        *float64               `protobuf:"fixed64,2,opt,name=shape_pt_lat,json=shapePtLat" json:"shape_pt_lat,omitempty"`
	ShapePtLon        *float64               `protobuf:"fixed64,3,opt,name=shape_pt_lon,json=shapePtLon" json:"shape_pt_lon,omitempty"`
	ShapePtSequence   *int32                 `protobuf:"varint,4,opt,name=shape_pt_sequence,json=shapePtSequence" json:"shape_pt_sequence,omitempty"`
	ShapeDistTraveled *float64               `protobuf:"fixed64,5,opt,name=shape_dist_traveled,json=shapeDistTraveled" json:"shape_dist_traveled,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShapeProto) Reset() {
	*x = ShapeProto{}
	mi := &file_transit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShapeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeProto) ProtoMessage() {}

func (x *ShapeProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeProto.ProtoReflect.Descriptor instead.
func (*ShapeProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{2}
}

func (x *ShapeProto) GetShapeId() string {
	if x != nil && x.ShapeId != nil {
		return *x.ShapeId
	}
	return ""
}

func (x *ShapeProto) GetShapePtLat() float64 {
	if x != nil && x.ShapePtLat != nil {
		return *x.ShapePtLat
	}
	return 0
}

func (x *ShapeProto) GetShapePtLon() float64 {
	if x != nil && x.ShapePtLon != nil {
		return *x.ShapePtLon
	}
	return 0
}

func (x *ShapeProto) GetShapePtSequence() int32 {
	if x != nil && x.ShapePtSequence != nil {
		return *x.ShapePtSequence
	}
	return 0
}

func (x *ShapeProto) GetShapeDistTraveled() float64 {
	if x != nil && x.ShapeDistTraveled != nil {
		return *x.ShapeDistTraveled
	}
	return 0
}

type StopProto struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StopId             *string                `protobuf:"bytes,1,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	StopCode           *string                `protobuf:"bytes,2,opt,name=stop_code,json=stopCode" json:"stop_code,omitempty"`
	StopName           *string                `protobuf:"bytes,3,opt,name=stop_name,json=stopName" json:"stop_name,omitempty"`
	StopDesc           *string                `protobuf:"bytes,4,opt,name=stop_desc,json=stopDesc" json:"stop_desc,omitempty"`
	StopLat            *float64               `protobuf:"fixed64,5,opt,name=stop_lat,json=stopLat" json:"stop_lat,omitempty"`
	StopLon            *float64               `protobuf:"fixed64,6,opt,name=stop_lon,json=stopLon" json:"stop_lon,omitempty"`
	ZoneId             *string                `protobuf:"bytes,7,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	StopUrl            *string                `protobuf:"bytes,8,opt,name=stop_url,json=stopUrl" json:"stop_url,omitempty"`
	LocationType       *int32                 `protobuf:"varint,9,opt,name=location_type,json=locationType" json:"location_type,omitempty"`
	ParentStation      *string                `protobuf:"bytes,10,opt,name=parent_station,json=parentStation" json:"parent_station,omitempty"`
	StopTimezone       *string                `protobuf:"bytes,11,opt,name=stop_timezone,json=stopTimezone" json:"stop_timezone,omitempty"`
	WheelchairBoarding *int32                 `protobuf:"varint,12,opt,name=wheelchair_boarding,json=wheelchairBoarding" json:"wheelchair_boarding,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopProto) Reset() {
	*x = StopProto{}
	mi := &file_transit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProto) ProtoMessage() {}

func (x *StopProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProto.ProtoReflect.Descriptor instead.
func (*StopProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{3}
}

func (x *StopProto) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *StopProto) GetStopCode() string {
	if x != nil && x.StopCode != nil {
		return *x.StopCode
	}
	return ""
}

func (x *StopProto) GetStopName() string {
	if x != nil && x.StopName != nil {
		return *x.StopName
	}
	return ""
}

func (x *StopProto) GetStopDesc() string {
	if x != nil && x.StopDesc != nil {
		return *x.StopDesc
	}
	return ""
}

func (x *StopProto) GetStopLat() float64 {
	if x != nil && x.StopLat != nil {
		return *x.StopLat
	}
	return 0
}

func (x *StopProto) GetStopLon() float64 {
	if x != nil && x.StopLon != nil {
		return *x.StopLon
	}
	return 0
}

func (x *StopProto) GetZoneId() string {
	if x != nil && x.ZoneId != nil {
		return *x.ZoneId
	}
	return ""
}

func (x *StopProto) GetStopUrl() string {
	if x != nil && x.StopUrl != nil {
		return *x.StopUrl
	}
	return ""
}

func (x *StopProto) GetLocationType() int32 {
	if x != nil && x.LocationType != nil {
		return *x.LocationType
	}
	return 0
}

func (x *StopProto) GetParentStation() string {
	if x != nil && x.ParentStation != nil {
		return *x.ParentStation
	}
	return ""
}

func (x *StopProto) GetStopTimezone() string {
	if x != nil && x.StopTimezone != nil {
		return *x.StopTimezone
	}
	return ""
}

func (x *StopProto) GetWheelchairBoarding() int32 {
	if x != nil && x.WheelchairBoarding != nil {
		return *x.WheelchairBoarding
	}
	return 0
}

type StopTimeProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TripId            *string                `protobuf:"bytes,1,opt,name=trip_id,json=tripId" json:"trip_id,omitempty"`
	ArrivalTime       *string                `protobuf:"bytes,2,opt,name=arrival_time,json=arrivalTime" json:"arrival_time,omitempty"`
	DepartureTime     *string                `protobuf:"bytes,3,opt,name=departure_time,json=departureTime" json:"departure_time,omitempty"`
	StopId            *string                `protobuf:"bytes,4,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	StopSequence      *int32                 `protobuf:"varint,5,opt,name=stop_sequence,json=stopSequence" json:"stop_sequence,omitempty"`
	StopHeadsign      *string                `protobuf:"bytes,6,opt,name=stop_headsign,json=stopHeadsign" json:"stop_headsign,omitempty"`
	PickupType        *int32                 `protobuf:"varint,7,opt,name=pickup_type,json=pickupType" json:"pickup_type,omitempty"`
	DropOffType       *int32                 `protobuf:"varint,8,opt,name=drop_off_type,json=dropOffType" json:"drop_off_type,omitempty"`
	ShapeDistTraveled *float64               `protobuf:"fixed64,9,opt,name=shape_dist_traveled,json=shapeDistTraveled" json:"shape_dist_traveled,omitempty"`
	Timepoint         *int32                 `protobuf:"varint,10,opt,name=timepoint" json:"timepoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StopTimeProto) Reset() {
	*x = StopTimeProto{}
	mi := &file_transit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTimeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimeProto) ProtoMessage() {}

func (x *StopTimeProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimeProto.ProtoReflect.Descriptor instead.
func (*StopTimeProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{4}
}

func (x *StopTimeProto) GetTripId() string {
	if x != nil && x.TripId != nil {
		return *x.TripId
	}
	return ""
}

func (x *StopTimeProto) GetArrivalTime() string {
	if x != nil && x.ArrivalTime != nil {
		return *x.ArrivalTime
	}
	return ""
}

func (x *StopTimeProto) GetDepartureTime() string {
	if x != nil && x.DepartureTime != nil {
		return *x.DepartureTime
	}
	return ""
}

func (x *StopTimeProto) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *StopTimeProto) GetStopSequence() int32 {
	if x != nil && x.StopSequence != nil {
		return *x.StopSequence
	}
	return 0
}

func (x *StopTimeProto) GetStopHeadsign() string {
	if x != nil && x.StopHeadsign != nil {
		return *x.StopHeadsign
	}
	return ""
}

func (x *StopTimeProto) GetPickupType() int32 {
	if x != nil && x.PickupType != nil {
		return *x.PickupType
	}
	return 0
}

func (x *StopTimeProto) GetDropOffType() int32 {
	if x != nil && x.DropOffType != nil {
		return *x.DropOffType
	}
	return 0
}

func (x *StopTimeProto) GetShapeDistTraveled() float64 {
	if x != nil && x.ShapeDistTraveled != nil {
		return *x.ShapeDistTraveled
	}
	return 0
}

func (x *StopTimeProto) GetTimepoint() int32 {
	if x != nil && x.Timepoint != nil {
		return *x.Timepoint
	}
	return 0
}

type AlertEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Alert         *AlertProto            `protobuf:"bytes,2,opt,name=alert" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEntityProto) Reset() {
	*x = AlertEntityProto{}
	mi := &file_transit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEntityProto) ProtoMessage() {}

func (x *AlertEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEntityProto.ProtoReflect.Descriptor instead.
func (*AlertEntityProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{5}
}

func (x *AlertEntityProto) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *AlertEntityProto) GetAlert() *AlertProto {
	if x != nil {
		return x.Alert
	}
	return nil
}

type AlertProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivePeriod    []*ActivePeriodProto   `protobuf:"bytes,1,rep,name=active_period,json=activePeriod" json:"active_period,omitempty"`
	InformedEntity  []*InformedEntityProto `protobuf:"bytes,2,rep,name=informed_entity,json=informedEntity" json:"informed_entity,omitempty"`
	Cause           *int32                 `protobuf:"varint,3,opt,name=cause" json:"cause,omitempty"`
	Effect          *int32                 `protobuf:"varint,4,opt,name=effect" json:"effect,omitempty"`
	HeaderText      *TranslatedStringProto `protobuf:"bytes,5,opt,name=header_text,json=headerText" json:"header_text,omitempty"`
	DescriptionText *TranslatedStringProto `protobuf:"bytes,6,opt,name=description_text,json=descriptionText" json:"description_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlertProto) Reset() {
	*x = AlertProto{}
	mi := &file_transit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertProto) ProtoMessage() {}

func (x *AlertProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertProto.ProtoReflect.Descriptor instead.
func (*AlertProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{6}
}

func (x *AlertProto) GetActivePeriod() []*ActivePeriodProto {
	if x != nil {
		return x.ActivePeriod
	}
	return nil
}

func (x *AlertProto) GetInformedEntity() []*InformedEntityProto {
	if x != nil {
		return x.InformedEntity
	}
	return nil
}

func (x *AlertProto) GetCause() int32 {
	if x != nil && x.Cause != nil {
		return *x.Cause
	}
	return 0
}

func (x *AlertProto) GetEffect() int32 {
	if x != nil && x.Effect != nil {
		return *x.Effect
	}
	return 0
}

func (x *AlertProto) GetHeaderText() *TranslatedStringProto {
	if x != nil {
		return x.HeaderText
	}
	return nil
}

func (x *AlertProto) GetDescriptionText() *TranslatedStringProto {
	if x != nil {
		return x.DescriptionText
	}
	return nil
}

type ActivePeriodProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *int64                 `protobuf:"varint,1,opt,name=start" json:"start,omitempty"`
	End           *int64                 `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivePeriodProto) Reset() {
	*x = ActivePeriodProto{}
	mi := &file_transit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivePeriodProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivePeriodProto) ProtoMessage() {}

func (x *ActivePeriodProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivePeriodProto.ProtoReflect.Descriptor instead.
func (*ActivePeriodProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{7}
}

func (x *ActivePeriodProto) GetStart() int64 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *ActivePeriodProto) GetEnd() int64 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

type InformedEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgencyId      *string                `protobuf:"bytes,1,opt,name=agency_id,json=agencyId" json:"agency_id,omitempty"`
	RouteId       *string                `protobuf:"bytes,2,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	RouteType     *int32                 `protobuf:"varint,3,opt,name=route_type,json=routeType" json:"route_type,omitempty"`
	StopId        *string                `protobuf:"bytes,4,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InformedEntityProto) Reset() {
	*x = InformedEntityProto{}
	mi := &file_transit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InformedEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformedEntityProto) ProtoMessage() {}

func (x *InformedEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformedEntityProto.ProtoReflect.Descriptor instead.
func (*InformedEntityProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{8}
}

func (x *InformedEntityProto) GetAgencyId() string {
	if x != nil && x.AgencyId != nil {
		return *x.AgencyId
	}
	return ""
}

func (x *InformedEntityProto) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *InformedEntityProto) GetRouteType() int32 {
	if x != nil && x.RouteType != nil {
		return *x.RouteType
	}
	return 0
}

func (x *InformedEntityProto) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

type TranslatedStringProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   []*TranslationProto    `protobuf:"bytes,1,rep,name=translation" json:"translation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslatedStringProto) Reset() {
	*x = TranslatedStringProto{}
	mi := &file_transit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslatedStringProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatedStringProto) ProtoMessage() {}

func (x *TranslatedStringProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatedStringProto.ProtoReflect.Descriptor instead.
func (*TranslatedStringProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{9}
}

func (x *TranslatedStringProto) GetTranslation() []*TranslationProto {
	if x != nil {
		return x.Translation
	}
	return nil
}

type TranslationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Language      *string                `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationProto) Reset() {
	*x = TranslationProto{}
	mi := &file_transit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationProto) ProtoMessage() {}

func (x *TranslationProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationProto.ProtoReflect.Descriptor instead.
func (*TranslationProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{10}
}

func (x *TranslationProto) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *TranslationProto) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type TripUpdateEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TripUpdate    *TripUpdateProto       `protobuf:"bytes,2,opt,name=trip_update,json=tripUpdate" json:"trip_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripUpdateEntityProto) Reset() {
	*x = TripUpdateEntityProto{}
	mi := &file_transit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdateEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdateEntityProto) ProtoMessage() {}

func (x *TripUpdateEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdateEntityProto.ProtoReflect.Descriptor instead.
func (*TripUpdateEntityProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{11}
}

func (x *TripUpdateEntityProto) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *TripUpdateEntityProto) GetTripUpdate() *TripUpdateProto {
	if x != nil {
		return x.TripUpdate
	}
	return nil
}

type TripUpdateProto struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Trip           *TripDescriptorProto    `protobuf:"bytes,1,opt,name=trip" json:"trip,omitempty"`
	Vehicle        *VehicleDescriptorProto `protobuf:"bytes,2,opt,name=vehicle" json:"vehicle,omitempty"`
	StopTimeUpdate []*StopTimeUpdateProto  `protobuf:"bytes,3,rep,name=stop_time_update,json=stopTimeUpdate" json:"stop_time_update,omitempty"`
	Timestamp      *int64                  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TripUpdateProto) Reset() {
	*x = TripUpdateProto{}
	mi := &file_transit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdateProto) ProtoMessage() {}

func (x *TripUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdateProto.ProtoReflect.Descriptor instead.
func (*TripUpdateProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{12}
}

func (x *TripUpdateProto) GetTrip() *TripDescriptorProto {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *TripUpdateProto) GetVehicle() *VehicleDescriptorProto {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *TripUpdateProto) GetStopTimeUpdate() []*StopTimeUpdateProto {
	if x != nil {
		return x.StopTimeUpdate
	}
	return nil
}

func (x *TripUpdateProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type TripDescriptorProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TripId               *string                `protobuf:"bytes,1,opt,name=trip_id,json=tripId" json:"trip_id,omitempty"`
	RouteId              *string                `protobuf:"bytes,2,opt,name=route_id,json=routeId" json:"route_id,omitempty"`
	DirectionId          *int32                 `protobuf:"varint,3,opt,name=direction_id,json=directionId" json:"direction_id,omitempty"`
	ScheduleRelationship *int32                 `protobuf:"varint,4,opt,name=schedule_relationship,json=scheduleRelationship" json:"schedule_relationship,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TripDescriptorProto) Reset() {
	*x = TripDescriptorProto{}
	mi := &file_transit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDescriptorProto) ProtoMessage() {}

func (x *TripDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDescriptorProto.ProtoReflect.Descriptor instead.
func (*TripDescriptorProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{13}
}

func (x *TripDescriptorProto) GetTripId() string {
	if x != nil && x.TripId != nil {
		return *x.TripId
	}
	return ""
}

func (x *TripDescriptorProto) GetRouteId() string {
	if x != nil && x.RouteId != nil {
		return *x.RouteId
	}
	return ""
}

func (x *TripDescriptorProto) GetDirectionId() int32 {
	if x != nil && x.DirectionId != nil {
		return *x.DirectionId
	}
	return 0
}

func (x *TripDescriptorProto) GetScheduleRelationship() int32 {
	if x != nil && x.ScheduleRelationship != nil {
		return *x.ScheduleRelationship
	}
	return 0
}

type VehicleDescriptorProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Label         *string                `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleDescriptorProto) Reset() {
	*x = VehicleDescriptorProto{}
	mi := &file_transit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleDescriptorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleDescriptorProto) ProtoMessage() {}

func (x *VehicleDescriptorProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleDescriptorProto.ProtoReflect.Descriptor instead.
func (*VehicleDescriptorProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{14}
}

func (x *VehicleDescriptorProto) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *VehicleDescriptorProto) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

type StopTimeUpdateProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StopSequence         *int32                 `protobuf:"varint,1,opt,name=stop_sequence,json=stopSequence" json:"stop_sequence,omitempty"`
	StopId               *string                `protobuf:"bytes,2,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	Arrival              *StopTimeEventProto    `protobuf:"bytes,3,opt,name=arrival" json:"arrival,omitempty"`
	Departure            *StopTimeEventProto    `protobuf:"bytes,4,opt,name=departure" json:"departure,omitempty"`
	ScheduleRelationship *int32                 `protobuf:"varint,5,opt,name=schedule_relationship,json=scheduleRelationship" json:"schedule_relationship,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StopTimeUpdateProto) Reset() {
	*x = StopTimeUpdateProto{}
	mi := &file_transit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTimeUpdateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimeUpdateProto) ProtoMessage() {}

func (x *StopTimeUpdateProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimeUpdateProto.ProtoReflect.Descriptor instead.
func (*StopTimeUpdateProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{15}
}

func (x *StopTimeUpdateProto) GetStopSequence() int32 {
	if x != nil && x.StopSequence != nil {
		return *x.StopSequence
	}
	return 0
}

func (x *StopTimeUpdateProto) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *StopTimeUpdateProto) GetArrival() *StopTimeEventProto {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *StopTimeUpdateProto) GetDeparture() *StopTimeEventProto {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *StopTimeUpdateProto) GetScheduleRelationship() int32 {
	if x != nil && x.ScheduleRelationship != nil {
		return *x.ScheduleRelationship
	}
	return 0
}

type StopTimeEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *int64                 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTimeEventProto) Reset() {
	*x = StopTimeEventProto{}
	mi := &file_transit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTimeEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTimeEventProto) ProtoMessage() {}

func (x *StopTimeEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTimeEventProto.ProtoReflect.Descriptor instead.
func (*StopTimeEventProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{16}
}

func (x *StopTimeEventProto) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type VehiclePositionEntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Vehicle       *VehiclePositionProto  `protobuf:"bytes,2,opt,name=vehicle" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclePositionEntityProto) Reset() {
	*x = VehiclePositionEntityProto{}
	mi := &file_transit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePositionEntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePositionEntityProto) ProtoMessage() {}

func (x *VehiclePositionEntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePositionEntityProto.ProtoReflect.Descriptor instead.
func (*VehiclePositionEntityProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{17}
}

func (x *VehiclePositionEntityProto) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *VehiclePositionEntityProto) GetVehicle() *VehiclePositionProto {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type VehiclePositionProto struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Trip            *TripDescriptorProto    `protobuf:"bytes,1,opt,name=trip" json:"trip,omitempty"`
	Vehicle         *VehicleDescriptorProto `protobuf:"bytes,2,opt,name=vehicle" json:"vehicle,omitempty"`
	Position        *GeoPositionProto       `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
	StopId          *string                 `protobuf:"bytes,4,opt,name=stop_id,json=stopId" json:"stop_id,omitempty"`
	CurrentStatus   *int32                  `protobuf:"varint,5,opt,name=current_status,json=currentStatus" json:"current_status,omitempty"`
	Timestamp       *int64                  `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	OccupancyStatus *int32                  `protobuf:"varint,7,opt,name=occupancy_status,json=occupancyStatus" json:"occupancy_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VehiclePositionProto) Reset() {
	*x = VehiclePositionProto{}
	mi := &file_transit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePositionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePositionProto) ProtoMessage() {}

func (x *VehiclePositionProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePositionProto.ProtoReflect.Descriptor instead.
func (*VehiclePositionProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{18}
}

func (x *VehiclePositionProto) GetTrip() *TripDescriptorProto {
	if x != nil {
		return x.Trip
	}
	return nil
}

func (x *VehiclePositionProto) GetVehicle() *VehicleDescriptorProto {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *VehiclePositionProto) GetPosition() *GeoPositionProto {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *VehiclePositionProto) GetStopId() string {
	if x != nil && x.StopId != nil {
		return *x.StopId
	}
	return ""
}

func (x *VehiclePositionProto) GetCurrentStatus() int32 {
	if x != nil && x.CurrentStatus != nil {
		return *x.CurrentStatus
	}
	return 0
}

func (x *VehiclePositionProto) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *VehiclePositionProto) GetOccupancyStatus() int32 {
	if x != nil && x.OccupancyStatus != nil {
		return *x.OccupancyStatus
	}
	return 0
}

type GeoPositionProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float64               `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Bearing       *float64               `protobuf:"fixed64,3,opt,name=bearing" json:"bearing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPositionProto) Reset() {
	*x = GeoPositionProto{}
	mi := &file_transit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPositionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPositionProto) ProtoMessage() {}

func (x *GeoPositionProto) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPositionProto.ProtoReflect.Descriptor instead.
func (*GeoPositionProto) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{19}
}

func (x *GeoPositionProto) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GeoPositionProto) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GeoPositionProto) GetBearing() float64 {
	if x != nil && x.Bearing != nil {
		return *x.Bearing
	}
	return 0
}

type VehiclePositionCollection struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Entities      []*VehiclePositionEntityProto `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	Timestamp     *int64                        `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclePositionCollection) Reset() {
	*x = VehiclePositionCollection{}
	mi := &file_transit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclePositionCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclePositionCollection) ProtoMessage() {}

func (x *VehiclePositionCollection) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclePositionCollection.ProtoReflect.Descriptor instead.
func (*VehiclePositionCollection) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{20}
}

func (x *VehiclePositionCollection) GetEntities() []*VehiclePositionEntityProto {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *VehiclePositionCollection) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type AlertCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*AlertEntityProto    `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	Timestamp     *int64                 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertCollection) Reset() {
	*x = AlertCollection{}
	mi := &file_transit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertCollection) ProtoMessage() {}

func (x *AlertCollection) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertCollection.ProtoReflect.Descriptor instead.
func (*AlertCollection) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{21}
}

func (x *AlertCollection) GetEntities() []*AlertEntityProto {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *AlertCollection) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type TripUpdateCollection struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entities      []*TripUpdateEntityProto `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	Timestamp     *int64                   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripUpdateCollection) Reset() {
	*x = TripUpdateCollection{}
	mi := &file_transit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripUpdateCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripUpdateCollection) ProtoMessage() {}

func (x *TripUpdateCollection) ProtoReflect() protoreflect.Message {
	mi := &file_transit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripUpdateCollection.ProtoReflect.Descriptor instead.
func (*TripUpdateCollection) Descriptor() ([]byte, []int) {
	return file_transit_proto_rawDescGZIP(), []int{22}
}

func (x *TripUpdateCollection) GetEntities() []*TripUpdateEntityProto {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *TripUpdateCollection) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_transit_proto protoreflect.FileDescriptor

const file_transit_proto_rawDesc = "" +
	"\n" +
	"\rtransit.proto\x12\n" +
	"transit.v1\"\xdc\x01\n" +
	"\tTripProto\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x17\n" +
	"\atrip_id\x18\x03 \x01(\tR\x06tripId\x12#\n" +
	"\rtrip_headsign\x18\x04 \x01(\tR\ftripHeadsign\x12!\n" +
	"\fdirection_id\x18\x05 \x01(\x05R\vdirectionId\x12\x19\n" +
	"\bblock_id\x18\x06 \x01(\tR\ablockId\x12\x19\n" +
	"\bshape_id\x18\a \x01(\tR\ashapeId\"\xbc\x02\n" +
	"\n" +
	"RouteProto\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1b\n" +
	"\tagency_id\x18\x02 \x01(\tR\bagencyId\x12(\n" +
	"\x10route_short_name\x18\x03 \x01(\tR\x0erouteShortName\x12&\n" +
	"\x0froute_long_name\x18\x04 \x01(\tR\rrouteLongName\x12\x1d\n" +
	"\n" +
	"route_desc\x18\x05 \x01(\tR\trouteDesc\x12\x1d\n" +
	"\n" +
	"route_type\x18\x06 \x01(\x05R\trouteType\x12\x1b\n" +
	"\troute_url\x18\a \x01(\tR\brouteUrl\x12\x1f\n" +
	"\vroute_color\x18\b \x01(\tR\n" +
	"routeColor\x12(\n" +
	"\x10route_text_color\x18\t \x01(\tR\x0erouteTextColor\"\xc7\x01\n" +
	"\n" +
	"ShapeProto\x12\x19\n" +
	"\bshape_id\x18\x01 \x01(\tR\ashapeId\x12 \n" +
	"\fshape_pt_lat\x18\x02 \x01(\x01R\n" +
	"shapePtLat\x12 \n" +
	"\fshape_pt_lon\x18\x03 \x01(\x01R\n" +
	"shapePtLon\x12*\n" +
	"\x11shape_pt_sequence\x18\x04 \x01(\x05R\x0fshapePtSequence\x12.\n" +
	"\x13shape_dist_traveled\x18\x05 \x01(\x01R\x11shapeDistTraveled\"\x87\x03\n" +
	"\tStopProto\x12\x17\n" +
	"\astop_id\x18\x01 \x01(\tR\x06stopId\x12\x1b\n" +
	"\tstop_code\x18\x02 \x01(\tR\bstopCode\x12\x1b\n" +
	"\tstop_name\x18\x03 \x01(\tR\bstopName\x12\x1b\n" +
	"\tstop_desc\x18\x04 \x01(\tR\bstopDesc\x12\x19\n" +
	"\bstop_lat\x18\x05 \x01(\x01R\astopLat\x12\x19\n" +
	"\bstop_lon\x18\x06 \x01(\x01R\astopLon\x12\x17\n" +
	"\azone_id\x18\a \x01(\tR\x06zoneId\x12\x19\n" +
	"\bstop_url\x18\b \x01(\tR\astopUrl\x12#\n" +
	"\rlocation_type\x18\t \x01(\x05R\flocationType\x12%\n" +
	"\x0eparent_station\x18\n" +
	" \x01(\tR\rparentStation\x12#\n" +
	"\rstop_timezone\x18\v \x01(\tR\fstopTimezone\x12/\n" +
	"\x13wheelchair_boarding\x18\f \x01(\x05R\x12wheelchairBoarding\"\xe8\x02\n" +
	"\rStopTimeProto\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12!\n" +
	"\farrival_time\x18\x02 \x01(\tR\varrivalTime\x12%\n" +
	"\x0edeparture_time\x18\x03 \x01(\tR\rdepartureTime\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\x12#\n" +
	"\rstop_sequence\x18\x05 \x01(\x05R\fstopSequence\x12#\n" +
	"\rstop_headsign\x18\x06 \x01(\tR\fstopHeadsign\x12\x1f\n" +
	"\vpickup_type\x18\a \x01(\x05R\n" +
	"pickupType\x12\"\n" +
	"\rdrop_off_type\x18\b \x01(\x05R\vdropOffType\x12.\n" +
	"\x13shape_dist_traveled\x18\t \x01(\x01R\x11shapeDistTraveled\x12\x1c\n" +
	"\ttimepoint\x18\n" +
	" \x01(\x05R\ttimepoint\"P\n" +
	"\x10AlertEntityProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x05alert\x18\x02 \x01(\v2\x16.transit.v1.AlertProtoR\x05alert\"\xda\x02\n" +
	"\n" +
	"AlertProto\x12B\n" +
	"\ractive_period\x18\x01 \x03(\v2\x1d.transit.v1.ActivePeriodProtoR\factivePeriod\x12H\n" +
	"\x0finformed_entity\x18\x02 \x03(\v2\x1f.transit.v1.InformedEntityProtoR\x0einformedEntity\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\x05R\x05cause\x12\x16\n" +
	"\x06effect\x18\x04 \x01(\x05R\x06effect\x12B\n" +
	"\vheader_text\x18\x05 \x01(\v2!.transit.v1.TranslatedStringProtoR\n" +
	"headerText\x12L\n" +
	"\x10description_text\x18\x06 \x01(\v2!.transit.v1.TranslatedStringProtoR\x0fdescriptionText\";\n" +
	"\x11ActivePeriodProto\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\x85\x01\n" +
	"\x13InformedEntityProto\x12\x1b\n" +
	"\tagency_id\x18\x01 \x01(\tR\bagencyId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1d\n" +
	"\n" +
	"route_type\x18\x03 \x01(\x05R\trouteType\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\"W\n" +
	"\x15TranslatedStringProto\x12>\n" +
	"\vtranslation\x18\x01 \x03(\v2\x1c.transit.v1.TranslationProtoR\vtranslation\"B\n" +
	"\x10TranslationProto\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"e\n" +
	"\x15TripUpdateEntityProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\vtrip_update\x18\x02 \x01(\v2\x1b.transit.v1.TripUpdateProtoR\n" +
	"tripUpdate\"\xed\x01\n" +
	"\x0fTripUpdateProto\x123\n" +
	"\x04trip\x18\x01 \x01(\v2\x1f.transit.v1.TripDescriptorProtoR\x04trip\x12<\n" +
	"\avehicle\x18\x02 \x01(\v2\".transit.v1.VehicleDescriptorProtoR\avehicle\x12I\n" +
	"\x10stop_time_update\x18\x03 \x03(\v2\x1f.transit.v1.StopTimeUpdateProtoR\x0estopTimeUpdate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa1\x01\n" +
	"\x13TripDescriptorProto\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12!\n" +
	"\fdirection_id\x18\x03 \x01(\x05R\vdirectionId\x123\n" +
	"\x15schedule_relationship\x18\x04 \x01(\x05R\x14scheduleRelationship\">\n" +
	"\x16VehicleDescriptorProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x80\x02\n" +
	"\x13StopTimeUpdateProto\x12#\n" +
	"\rstop_sequence\x18\x01 \x01(\x05R\fstopSequence\x12\x17\n" +
	"\astop_id\x18\x02 \x01(\tR\x06stopId\x128\n" +
	"\aarrival\x18\x03 \x01(\v2\x1e.transit.v1.StopTimeEventProtoR\aarrival\x12<\n" +
	"\tdeparture\x18\x04 \x01(\v2\x1e.transit.v1.StopTimeEventProtoR\tdeparture\x123\n" +
	"\x15schedule_relationship\x18\x05 \x01(\x05R\x14scheduleRelationship\"(\n" +
	"\x12StopTimeEventProto\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"h\n" +
	"\x1aVehiclePositionEntityProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\avehicle\x18\x02 \x01(\v2 .transit.v1.VehiclePositionProtoR\avehicle\"\xcc\x02\n" +
	"\x14VehiclePositionProto\x123\n" +
	"\x04trip\x18\x01 \x01(\v2\x1f.transit.v1.TripDescriptorProtoR\x04trip\x12<\n" +
	"\avehicle\x18\x02 \x01(\v2\".transit.v1.VehicleDescriptorProtoR\avehicle\x128\n" +
	"\bposition\x18\x03 \x01(\v2\x1c.transit.v1.GeoPositionProtoR\bposition\x12\x17\n" +
	"\astop_id\x18\x04 \x01(\tR\x06stopId\x12%\n" +
	"\x0ecurrent_status\x18\x05 \x01(\x05R\rcurrentStatus\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10occupancy_status\x18\a \x01(\x05R\x0foccupancyStatus\"f\n" +
	"\x10GeoPositionProto\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\abearing\x18\x03 \x01(\x01R\abearing\"}\n" +
	"\x19VehiclePositionCollection\x12B\n" +
	"\bentities\x18\x01 \x03(\v2&.transit.v1.VehiclePositionEntityProtoR\bentities\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"i\n" +
	"\x0fAlertCollection\x128\n" +
	"\bentities\x18\x01 \x03(\v2\x1c.transit.v1.AlertEntityProtoR\bentities\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"s\n" +
	"\x14TripUpdateCollection\x12=\n" +
	"\bentities\x18\x01 \x03(\v2!.transit.v1.TripUpdateEntityProtoR\bentities\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestampB9Z7github.com/peterbishop/studious-waffle/server/protodatab\beditionsp\xe8\a"

var (
	file_transit_proto_rawDescOnce sync.Once
	file_transit_proto_rawDescData []byte
)

func file_transit_proto_rawDescGZIP() []byte {
	file_transit_proto_rawDescOnce.Do(func() {
		file_transit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transit_proto_rawDesc), len(file_transit_proto_rawDesc)))
	})
	return file_transit_proto_rawDescData
}

var file_transit_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_transit_proto_goTypes = []any{
	(*TripProto)(nil),                  // 0: transit.v1.TripProto
	(*RouteProto)(nil),                 // 1: transit.v1.RouteProto
	(*ShapeProto)(nil),                 // 2: transit.v1.ShapeProto
	(*StopProto)(nil),                  // 3: transit.v1.StopProto
	(*StopTimeProto)(nil),              // 4: transit.v1.StopTimeProto
	(*AlertEntityProto)(nil),           // 5: transit.v1.AlertEntityProto
	(*AlertProto)(nil),                 // 6: transit.v1.AlertProto
	(*ActivePeriodProto)(nil),          // 7: transit.v1.ActivePeriodProto
	(*InformedEntityProto)(nil),        // 8: transit.v1.InformedEntityProto
	(*TranslatedStringProto)(nil),      // 9: transit.v1.TranslatedStringProto
	(*TranslationProto)(nil),           // 10: transit.v1.TranslationProto
	(*TripUpdateEntityProto)(nil),      // 11: transit.v1.TripUpdateEntityProto
	(*TripUpdateProto)(nil),            // 12: transit.v1.TripUpdateProto
	(*TripDescriptorProto)(nil),        // 13: transit.v1.TripDescriptorProto
	(*VehicleDescriptorProto)(nil),     // 14: transit.v1.VehicleDescriptorProto
	(*StopTimeUpdateProto)(nil),        // 15: transit.v1.StopTimeUpdateProto
	(*StopTimeEventProto)(nil),         // 16: transit.v1.StopTimeEventProto
	(*VehiclePositionEntityProto)(nil), // 17: transit.v1.VehiclePositionEntityProto
	(*VehiclePositionProto)(nil),       // 18: transit.v1.VehiclePositionProto
	(*GeoPositionProto)(nil),           // 19: transit.v1.GeoPositionProto
	(*VehiclePositionCollection)(nil),  // 20: transit.v1.VehiclePositionCollection
	(*AlertCollection)(nil),            // 21: transit.v1.AlertCollection
	(*TripUpdateCollection)(nil),       // 22: transit.v1.TripUpdateCollection
}
var file_transit_proto_depIdxs = []int32{
	6,  // 0: transit.v1.AlertEntityProto.alert:type_name -> transit.v1.AlertProto
	7,  // 1: transit.v1.AlertProto.active_period:type_name -> transit.v1.ActivePeriodProto
	8,  // 2: transit.v1.AlertProto.informed_entity:type_name -> transit.v1.InformedEntityProto
	9,  // 3: transit.v1.AlertProto.header_text:type_name -> transit.v1.TranslatedStringProto
	9,  // 4: transit.v1.AlertProto.description_text:type_name -> transit.v1.TranslatedStringProto
	10, // 5: transit.v1.TranslatedStringProto.translation:type_name -> transit.v1.TranslationProto
	12, // 6: transit.v1.TripUpdateEntityProto.trip_update:type_name -> transit.v1.TripUpdateProto
	13, // 7: transit.v1.TripUpdateProto.trip:type_name -> transit.v1.TripDescriptorProto
	14, // 8: transit.v1.TripUpdateProto.vehicle:type_name -> transit.v1.VehicleDescriptorProto
	15, // 9: transit.v1.TripUpdateProto.stop_time_update:type_name -> transit.v1.StopTimeUpdateProto
	16, // 10: transit.v1.StopTimeUpdateProto.arrival:type_name -> transit.v1.StopTimeEventProto
	16, // 11: transit.v1.StopTimeUpdateProto.departure:type_name -> transit.v1.StopTimeEventProto
	18, // 12: transit.v1.VehiclePositionEntityProto.vehicle:type_name -> transit.v1.VehiclePositionProto
	13, // 13: transit.v1.VehiclePositionProto.trip:type_name -> transit.v1.TripDescriptorProto
	14, // 14: transit.v1.VehiclePositionProto.vehicle:type_name -> transit.v1.VehicleDescriptorProto
	19, // 15: transit.v1.VehiclePositionProto.position:type_name -> transit.v1.GeoPositionProto
	17, // 16: transit.v1.VehiclePositionCollection.entities:type_name -> transit.v1.VehiclePositionEntityProto
	5,  // 17: transit.v1.AlertCollection.entities:type_name -> transit.v1.AlertEntityProto
	11, // 18: transit.v1.TripUpdateCollection.entities:type_name -> transit.v1.TripUpdateEntityProto
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_transit_proto_init() }
func file_transit_proto_init() {
	if File_transit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transit_proto_rawDesc), len(file_transit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transit_proto_goTypes,
		DependencyIndexes: file_transit_proto_depIdxs,
		MessageInfos:      file_transit_proto_msgTypes,
	}.Build()
	File_transit_proto = out.File
	file_transit_proto_goTypes = nil
	file_transit_proto_depIdxs = nil
}
